// V2 대사 46줄 — Bus/규격/대사양식_v2.csv 에서 그대로 옮김.
// 이 파일을 고치는 대신 CSV를 고치고 다시 옮기세요 — 원본은 CSV입니다.

export const DIALOGUE_V2_GENRE_LABEL = { R: "로맨스", H: "공포", C: "블랙코미디" };

export const DIALOGUE_V2_LINES = [
  { genre: "R", seq: "01", text: "안녕하십니까, 저는… 저, 저는—", file: "vo_R_01.mp3" },
  { genre: "R", seq: "02", text: "아, 죄송해요! 시끄러웠죠. 저 오늘 면접이 있어서요. 태어나서 처음 보는 면접이라...", file: "vo_R_02.mp3" },
  { genre: "R", seq: "03", text: "안녕하십니까! 저는 사람 만나는 일이 세상에서 제일 좋—", file: "vo_R_03.mp3" },
  { genre: "R", seq: "04", text: "아, 왜 맨날 여기서!", file: "vo_R_04.mp3" },
  { genre: "R", seq: "05", text: "혹시 어느 회사 다니세요? 사원증 있으세요, 목에 거는 거?", file: "vo_R_05.mp3" },
  { genre: "R", seq: "06", text: "어머, 진짜요? 완전 대단하다...", file: "vo_R_06.mp3" },
  { genre: "R", seq: "07", text: "...차도남 인가. 멋있다", file: "vo_R_07.mp3" },
  { genre: "R", seq: "08", text: "4시면 끝물이잖아요. 저 혹시... 들러리 아닐까요?", file: "vo_R_08.mp3" },
  { genre: "R", seq: "09", text: "면접관들이 저 보고 딴생각하면 어쩌죠.", file: "vo_R_09.mp3" },
  { genre: "R", seq: "10", text: "…아니다.", file: "vo_R_10.mp3" },
  { genre: "R", seq: "11", text: "몇 번 버스 타세요?", file: "vo_R_11.mp3" },
  { genre: "R", seq: "12", text: "...사실 진짜 떨려요.", file: "vo_R_12.mp3" },
  { genre: "R", seq: "13", text: "저기 카페 보이시죠? 저기 살아요. 부모님이 하시는 건데... 나중에 놀러 오세요.", file: "vo_R_13.mp3" },
  { genre: "R", seq: "14", text: "응원해 주세요! 저 4시예요. 4시에 딱 1분만... 생각해 주세요!", file: "vo_R_14.mp3" },
  { genre: "H", seq: "01", text: "저기 유리에 뭐 붙어 있던 거, 읽으셨어요?", file: "vo_H_01.mp3" },
  { genre: "H", seq: "02", text: "저거 아무도 못 찾아요. 그런 거 찾는 사람, 없어요.", file: "vo_H_02.mp3" },
  { genre: "H", seq: "03", text: "아까 저 고양이, 어느 쪽으로 뛰어갔는지 보셨어요?", file: "vo_H_03.mp3" },
  { genre: "H", seq: "04", text: "그 고양이, 당신 보고 놀란 게 아니었을 거예요.", file: "vo_H_04.mp3" },
  { genre: "H", seq: "05", text: "그 소리는요. 놀라는 소리 같지 않던데.", file: "vo_H_05.mp3" },
  { genre: "H", seq: "06", text: "카페 문 열리는 거 보셨죠. 그 안에 있던 사람들, 손 흔드는 거요?", file: "vo_H_06.mp3" },
  { genre: "H", seq: "07", text: "저는 잡으려는 거처럼 보였는데.", file: "vo_H_07.mp3" },
  { genre: "H", seq: "08", text: "…그럴 줄 알았어요.", file: "vo_H_08.mp3" },
  { genre: "H", seq: "09", text: "저도 방금 왔어요. 저기 커브 돌 때쯤요.", file: "vo_H_09.mp3" },
  { genre: "H", seq: "10", text: "여기 얼마나 앉아 계셨어요?", file: "vo_H_10.mp3" },
  { genre: "H", seq: "11", text: "…제가 오기 전부터요?", file: "vo_H_11.mp3" },
  { genre: "H", seq: "12", text: "그 고양이, 왼쪽에서 한 번 더 울었죠. 그건 못 보셨을 거예요.", file: "vo_H_12.mp3" },
  { genre: "H", seq: "13", text: "그쪽엔 아무것도 없어요. 지금은.", file: "vo_H_13.mp3" },
  { genre: "H", seq: "14", text: "먼저 가세요.", file: "vo_H_14.mp3" },
  { genre: "C", seq: "01", text: "아이고, 무릎이야.", file: "vo_C_01.mp3" },
  { genre: "C", seq: "02", text: "그놈이 또 여기 왔었네.", file: "vo_C_02.mp3" },
  { genre: "C", seq: "03", text: "저거. 안 봤으면 잘 보고.", file: "vo_C_03.mp3" },
  { genre: "C", seq: "04", text: "며칠째예요.", file: "vo_C_04.mp3" },
  { genre: "C", seq: "05", text: "밥은 주는데, 얼굴을 안 비쳐.", file: "vo_C_05.mp3" },
  { genre: "C", seq: "06", text: "그쪽에서는 못 봤어요? 그 놈.", file: "vo_C_06.mp3" },
  { genre: "C", seq: "07", text: "지가 뭐 대단한 놈인 줄 알고.", file: "vo_C_07.mp3" },
  { genre: "C", seq: "08", text: "밥그릇도 안 건드리고. 그러면서 오기는 와요.", file: "vo_C_08.mp3" },
  { genre: "C", seq: "09", text: "아이 씨, 거미줄이야.", file: "vo_C_09.mp3" },
  { genre: "C", seq: "10", text: "웃지 마요. 나 심각해.", file: "vo_C_10.mp3" },
  { genre: "C", seq: "11", text: "…아까도 없었는데.", file: "vo_C_11.mp3" },
  { genre: "C", seq: "12", text: "…또 그 자리에 없네.", file: "vo_C_12.mp3" },
  { genre: "C", seq: "13", text: "매번 이 시간엔 지나가더니.", file: "vo_C_13.mp3" },
  { genre: "C", seq: "14", text: "이거 봐요. 안 찢어진 거.", file: "vo_C_14.mp3" },
  { genre: "C", seq: "15", text: "이 사람, 우리 할아버지. 3년 전에 갔어요.", file: "vo_C_15.mp3" },
  { genre: "C", seq: "16", text: "고양이는 그냥 옆에 있던 거예요.", file: "vo_C_16.mp3" },
  { genre: "C", seq: "17", text: "…그냥, 붙여요. 매번.", file: "vo_C_17.mp3" },
  { genre: "C", seq: "18", text: "이거 뗄 때 됐는데. 또 새 걸로 붙여야겠네.", file: "vo_C_18.mp3" },
];

export const DIALOGUE_V2_SLOT_ID = (genre, seq) => `vo2.${genre}.${seq}`;

